//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tools.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TOOLS_FORM                  101
#define IDR_MAINFRAME                   128
#define IDR_MAINBAR                     129
#define IDR_TOOLSTYPE                   130
#define IDD_GENSERIAL                   131
#define IDI_INDICATOR                   132
#define IDB_SPLASH                      148
#define IDB_HELPLOGO                    160
#define IDB_MENUCHECKED                 166
#define IDB_DLGLEFTLOGO                 194
#define IDR_TEXT_NSA                    198
#define IDD_REGISTER                    199
#define IDB_DLGTOPLOGO                  200
#define IDD_AGENT                       201
#define IDB_MENUCHECKED1                202
#define IDD_GENBASE                     203
#define IDD_BASERMRIGHT                 204
#define IDI_STRATEGY                    204
#define IDD_FILETIME                    205
#define IDD_GENDOMAIN                   206
#define IDI_BALANG                      207
#define IDD_GENCODETBL                  207
#define IDD_GENNAMEENU                  208
#define IDD_GENEVA                      209
#define IDB_BALANG                      212
#define IDI_STRATEGY2                   230
#define IDC_URL_ADDRESS                 1000
#define IDC_SAVE                        1001
#define IDC_SAVEREG                     1002
#define IDC_EXPLORER                    1003
#define IDC_EXPLORER_DEST               1004
#define IDC_CODEJOCKEY                  1005
#define IDC_EXPLORER_QLSRC              1006
#define IDC_DESTFILE                    1007
#define IDC_URL_MAILME                  1008
#define IDC_EXPLORER_263SRC             1008
#define IDC_SRCPATH                     1009
#define IDC_USER                        1010
#define IDC_263SRCFILE                  1010
#define IDC_RADIO_ANN                   1011
#define IDC_RADIO_MID                   1012
#define IDC_RADIO_QUARTER               1013
#define IDC_RADIO_QUARTER3              1014
#define IDC_NEWFILE                     1015
#define IDC_DATETIME                    1016
#define IDC_REGCODE                     1048
#define IDC_PICTURE                     1076
#define IDC_USERNAME                    1078
#define IDC_SOFTNO                      1079
#define IDC_GOPURCHASE                  1081
#define IDC_DISPACHTITLE                1082
#define IDC_DISPATCHUSER                1083
#define IDC_EDIT_NSA                    1087
#define IDC_LEFTDAYS                    1088
#define IDC_LEFTDAYSTITLE               1089
#define IDC_SHARE_COUNT_B               1091
#define IDC_SHARE_COUNT_H               1092
#define IDC_REGISTERCODE                1092
#define IDC_SHARE_COUNT_NATIONAL        1093
#define IDC_SHARE_COUNT_CORP            1094
#define IDC_ASSET                       1095
#define IDC_EXPLORER_SRC                1095
#define IDC_DESTPATH                    1096
#define IDC_TIMECREATE                  1097
#define IDC_TIMEACCESS                  1098
#define IDC_SAVEDISPATCH                1098
#define IDC_TIMEWRITE                   1099
#define IDC_ERATE_DOLLAR                1099
#define IDC_ERATE_HKDOLLAR              1100
#define IDC_TAB1                        1101
#define IDC_PROFESSIONAL                1102
#define IDC_HOWTO_REG                   1139
#define IDC_STATIC_REGISTER             1140
#define IDC_COPY_SOFTNO                 1141
#define IDC_VERSION                     1170
#define IDC_RADIO_DEFAULT1              1171
#define IDC_RADIO_DEFAULT3              1172
#define ID_VIEW_MAINBARTEXTBOT          32771
#define IDW_MAINBAR                     32772
#define ID_VIEW_MAINBARTEXTRIGHT        32773
#define ID_VIEW_FULLSCREEN              32774
#define ID_TOOL_GENSERIAL               32775
#define ID_HELP_REGISTER                32776
#define ID_TOOL_OPENDBFILE              32777
#define ID_TOOL_GENBASE                 32779
#define ID_TOOL_BASERMCR                32781
#define ID_TOOL_FILETIME                32782
#define ID_TOOL_GENDOMAIN               32783
#define ID_TOOL_GENCODETBL              32784
#define ID_TOOL_GENNAMEENU              32787
#define ID_TOOL_GENEVA                  32789
#define IDS_TITLE_MAINBAR               45446
#define IDS_EVALUATEINFO                45447
#define IDS_EVALUATEFMT                 45448
#define IDS_USERNAMETOOSHORTFMT         45450
#define IDS_REGCODETOOSHORT             45451
#define IDS_INVALIDREGCODE              45452
#define IDS_AUTHORIZEDUSER_UNKNOWN      45453
#define IDS_REGCODE_UNPURCHASED         45454
#define IDS_BUILTREGCODE_FAILED         45455
#define IDS_STORESECRETFILE_FAILED      45456
#define IDS_SELECT_DIRECTORY            45457
#define IDS_ERROR_QIANLONGPATH          45458
#define IDS_ERROR_SELFDBPATH            45458
#define IDS_GENBASE_FINISH              45459
#define IDS_GENBASE_FAILED              45460
#define IDS_OPENFILE_FAILED             45461
#define IDS_GENBASE_REPORTFMT           45462
#define IDS_DOMAINFUND                  45463
#define IDS_GENBASE_NOSZZS              45464
#define IDS_GENBASE_FUNDINDEX           45465
#define IDS_BASERMRIGHT_PATHERROR       45466
#define IDS_FILETIME_PATHERROR          45467
#define IDS_BASERMRIGHT_NODESTPATH      45468
#define IDS_BASERMRIGHT_REPORTFMT       45469
#define IDS_BASERMRIGHT_ZIPOK           45470
#define IDS_FILETIME_REPORTFMT          45471
#define IDS_SECRET_ASSERTMESSAGE        45472
#define IDS_SECRET_FUNCLIMIT            45473
#define IDS_REGISTER_SUCCESS            45474
#define IDS_REGISTER_PURCHASED          45475
#define IDS_REGISTER_NOTIMELIMIT        45476
#define IDS_AFXCORE_SUNDAY              45477
#define IDS_AFXCORE_MONDAY              45478
#define IDS_AFXCORE_TUESDAY             45479
#define IDS_AFXCORE_WEDNESDAY           45480
#define IDS_AFXCORE_THURSDAY            45481
#define IDS_AFXCORE_FRIDAY              45482
#define IDS_AFXCORE_SATURDAY            45483
#define IDS_GENCODETBL_PATHERROR        45484
#define IDS_PATHERROR                   45484
#define IDS_GENCODETBL_NODESTPATH       45485
#define IDS_NODESTPATH                  45485
#define IDS_GENCODETBL_REPORTFMT        45486
#define IDS_PROFILE_SUBJECTSUPPORT      45487
#define IDS_GENDOMAIN_REPORTFMT         45488
#define IDS_GENSERIAL_STD               45489
#define IDS_GENSERIAL_PROF              45490
#define IDS_ERROR_QIANLONGDBPATH        45491
#define IDS_ERROR_OPENDESTFILE          45492
#define IDS_GENNAMEENU_REPORTFMT        45493

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
